# Generated by Django 5.0.1 on 2026-02-17 14:19

import apps.todo.domain.value_objects.task_id
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=apps.todo.domain.value_objects.task_id.ULIDGenerator.generate, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=apps.todo.domain.value_objects.task_id.ULIDGenerator.generate, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
