# Generated by Django 5.0.1 on 2026-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
